In [1]:
import pandas as pd
import numpy as np

In [2]:
#TASK1
df=pd.read_csv('csv.csv')

In [3]:
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [4]:
df.total = df['A'].sum()
print(total)

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [5]:
total_sum = df['Global_Sales'].sum()
print(total_sum)

8920.44


In [11]:
max_gamesale= df.loc[df['Global_Sales'].idxmax()]
print(max_gamesale)

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [12]:
avg_sale= df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print(avg_sale)

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [13]:
top_5= df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print(top_5)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [15]:
genre_sales = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
Top_NA_Sale = genre_sales['NA_Sales'].idxmax()
print(Top_NA_Sale)

Action


In [16]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [18]:
top_3 = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print(top_3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [21]:
total_global = df['Global_Sales'].sum()
m_share = (df.groupby('Genre')['Global_Sales'].sum() / total_global) * 100
print(m_share)

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [20]:
cor=df['NA_Sales'].corr(df['EU_Sales'])
print(cor)

0.7677267483702636


In [22]:
#TASK2

In [32]:
Eng_span = {
  "Hello": "Hola",
  "Bye": "adiós",
  "what":"qué"
}
word=(input("Enter english word: "))

if word in Eng_span:
    print("The translation is: ",Eng_span[word])
else:
    print("Word not found in dictionary.")

Enter english word:  Bye


The translation is:  adiós


In [69]:
#TASK3
def check_emails(emails):
    important= ["FAST", "deadline", "urgent", "project"]
    promotion= ["sale", "discount", "deal"]
    spam = ["lottery","click here"]
    important_emails = []
    promotions_emails = []
    spam_emails = []

    for i in emails:
        email_lower = i.lower()
        if any(word in email_lower for word in important):
            important_emails.append(i)
        elif any(word in email_lower for word in promotion):
            promotions_emails.append(i)
        elif any(word in email_lower for word in spam):
            spam_emails.append(i)
    return important_emails, promotions_emails, spam_emails

emails = [
    "Meeting at FAST auidtorium",
    "Discount for loyal Cake customers...",
    "Click here to claim your free money!"
]

important, promotions, spam = check_emails(emails)
print("Important Emails:",important)
print("Promotions Emails:",promotions)
print("Spam Emails:",spam)


Important Emails: []
Promotions Emails: ['Discount for loyal Cake customers...']
Spam Emails: ['Click here to claim your free money!']


In [50]:
#task4
# Store Simulation
def online_store_shopping_cart():
    products = {
        1: "Apple",
        2: "Mango",
        3: "Pine-apple",
        4: "Kiwi",
        5: "Strawberry",
    }
    
    shopping_cart = []
    print("Welcome to the Online Store!")
    print("Available products:")
    for key, value in products.items():
        print(f"{key}: {value}")
    print("Enter 'q' to quit and proceed to checkout.")
    
    while True:
        choice = input("Enter the number of the product to add to cart: ")
        
        if choice.lower() == 'x':
            break
        
        if choice.isdigit():
            choice = int(choice)
            if choice in products:
                shopping_cart.append(products[choice])
                print(f"'{products[choice]}' added to cart.")
            else:
                print("Invalid choice. Please select a valid product number.")
        else:
            print("Invalid input. Please enter a number or 'x' to quit.")
    
    print("\nYour Shopping Cart:")
    if shopping_cart:
        for item in shopping_cart:
            print(f"- {item}")    

online_store_shopping_cart()

Welcome to the Online Store!
Available products:
1: Apple
2: Mango
3: Pine-apple
4: Kiwi
5: Strawberry
Enter 'q' to quit and proceed to checkout.


Enter the number of the product to add to cart:  x



Your Shopping Cart:


In [65]:
#Task5
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])  
sum= arr1 + arr2 
prod= arr1 * arr2  
print("Addition: ",sum)
print("Product: ",prod)

Addition:  [5 7 9]
Product:  [ 4 10 18]


In [67]:
#Task6
arr1 = np.arange(12)
arr2 = arr1.reshape(3, 4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
#Task7
arr1 = [1, 2, 3, 4, 5]
arr2 = arr1[::-1]
print(arr2) 

[5, 4, 3, 2, 1]
